=== Codewithprajwol/PHP_Learning/xml/Dtd/firendlist.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT friendlist (friend+,bestfriend?)>
<!ELEMENT friend (name)>
<!ELEMENT bestfriend (name)>
<!ATTLIST bestfriend love CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>

=== Codewithprajwol/PHP_Learning/xml/Dtd/friendlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE friendlist SYSTEM "firendlist.dtd">
<friendlist>
    <friend>
        <name>Ram</name>
    </friend>
    <friend>
        <name>Sam</name>
    </friend>
    <friend>
        <name>Sam</name>
    </friend>
    <bestfriend love="very">
        <name>Hari</name>
    </bestfriend>
   
</friendlist>

<!--TODO: here ? can occure only one time whereas friend can occur many times -->
